# PokéAPI base URL and fetch limit
pokeapi.base-url=https://pokeapi.co/api/v2
pokeapi.fetch-limit=500
server.port=8080
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m
